name: Build extension

on:
  pull_request:
    branches: [main]

jobs:
  publish-extension:
    name: Compile and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Set up Node
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install dependencies
        run: yarn --cwd ./client

      # Build extension
      - name: Run build
        run: yarn --cwd ./client build

      # Run tests
      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn --cwd ./client test
